#pragma line 1 "./casting.cc" ::: -10
#pragma line 1 "./casting.cc" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 156 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 3
#pragma line 8 "<command line>" 2 ::: 133
#pragma line 1 "<built-in>" 2 ::: 134
#pragma line 1 "./casting.cc" 2 ::: 135
#pragma line 1 "./casting.h" 1 ::: 136
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/hls_stream.h" 1 ::: 141
#pragma line 66 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/hls_stream.h" ::: 142
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 143
#pragma line 58 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_enum.h" ::: 144
#pragma line 67 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/hls_stream.h" 2 ::: 217
#pragma line 78 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/hls_stream.h" ::: 221
#pragma line 6 "./casting.h" 2 ::: 311
#pragma line 2 "./casting.cc" 2 ::: 356
