#pragma line 1 "./casting.cc" ::: 0
#pragma line 1 "./casting.cc" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 156 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 13
#pragma line 8 "<command line>" 2 ::: 143
#pragma line 1 "<built-in>" 2 ::: 144
#pragma line 1 "./casting.cc" 2 ::: 145
#pragma line 1 "./casting.h" 1 ::: 146
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/hls_stream.h" 1 ::: 151
#pragma line 66 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/hls_stream.h" ::: 152
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 153
#pragma line 58 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_enum.h" ::: 154
#pragma line 67 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/hls_stream.h" 2 ::: 227
#pragma line 78 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/hls_stream.h" ::: 231
#pragma line 6 "./casting.h" 2 ::: 321
#pragma line 2 "./casting.cc" 2 ::: 366
