lappend pragmaStatus0 {pragma "INTERFACE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./casting.cc" location "wrapperAdmin" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'wrapperAdmin' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "INTERFACE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./casting.cc" location "wrapperAdmin" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'wrapperAdmin' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "INTERFACE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./casting.cc" location "wrapperAdmin" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'wrapperAdmin' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "INTERFACE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./casting.cc" location "wrapperAdmin" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'wrapperAdmin' does not exist in any synthesis source file."}
lappend pragmaStatus4 {pragma "INTERFACE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./casting.cc" location "wrapperAdmin" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'wrapperAdmin' does not exist in any synthesis source file."}
lappend pragmaStatus5 {pragma "DATAFLOW" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./casting.cc" location "wrapperAdmin" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'wrapperAdmin' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "INLINE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./casting.cc" location "buildResponseHead" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'buildResponseHead' does not exist in any synthesis source file."}
lappend pragmaStatus7 {pragma "INLINE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./casting.cc" location "buildResponse" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'buildResponse' does not exist in any synthesis source file."}
lappend pragmaStatus8 {pragma "INLINE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./casting.cc" location "forward" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'forward' does not exist in any synthesis source file."}
lappend pragmaStatus9 {pragma "INLINE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./casting.cc" location "newObject" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'newObject' does not exist in any synthesis source file."}
lappend pragmaStatus10 {pragma "INLINE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./casting.cc" location "wrapper_newObject" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'wrapper_newObject' does not exist in any synthesis source file."}
lappend pragmaStatus11 {pragma "INLINE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./casting.cc" location "readParameters_newObject" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'readParameters_newObject' does not exist in any synthesis source file."}
lappend pragmaStatus12 {pragma "INLINE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./casting.cc" location "wrapper_status" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'wrapper_status' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "INTERFACE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./wrapperAdmin.cc" location "wrapperAdmin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "INTERFACE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./wrapperAdmin.cc" location "wrapperAdmin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "INTERFACE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./wrapperAdmin.cc" location "wrapperAdmin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "INTERFACE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./wrapperAdmin.cc" location "wrapperAdmin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "INTERFACE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./wrapperAdmin.cc" location "wrapperAdmin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "DATAFLOW" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./wrapperAdmin.cc" location "wrapperAdmin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "INLINE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./wrapperAdmin.cc" location "buildResponseHead" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'buildResponseHead' does not exist in any synthesis source file."}
lappend pragmaStatus7 {pragma "INLINE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./wrapperAdmin.cc" location "buildResponse" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "INLINE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./wrapperAdmin.cc" location "forward" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "INLINE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./wrapperAdmin.cc" location "newObject" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "INLINE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./wrapperAdmin.cc" location "wrapper_newObject" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus11 {pragma "INLINE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./wrapperAdmin.cc" location "readParameters_newObject" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus12 {pragma "INLINE" source "/home/julian/workspace/devel/fpga_by_example/zedboard/DPR/src/IPs/zipFactory/src/hls/./wrapperAdmin.cc" location "wrapper_status" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
