// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "forward.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic forward::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic forward::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> forward::ap_ST_fsm_state1 = "1";
const sc_lv<2> forward::ap_ST_fsm_state2 = "10";
const sc_lv<32> forward::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> forward::ap_const_lv32_1 = "1";
const sc_lv<1> forward::ap_const_lv1_0 = "0";
const sc_lv<16> forward::ap_const_lv16_0 = "0000000000000000";
const sc_lv<16> forward::ap_const_lv16_1 = "1";
const sc_lv<1> forward::ap_const_lv1_1 = "1";
const bool forward::ap_const_boolean_1 = true;

forward::forward(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( src_V_empty_n );
    sensitive << ( tmp_fu_43_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( src_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_43_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( src_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_43_p2 );

    SC_METHOD(thread_it_1_fu_48_p2);
    sensitive << ( it_reg_32 );

    SC_METHOD(thread_src_V_blk_n);
    sensitive << ( src_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_43_p2 );

    SC_METHOD(thread_src_V_read);
    sensitive << ( src_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_43_p2 );

    SC_METHOD(thread_tmp_fu_43_p2);
    sensitive << ( src_V_empty_n );
    sensitive << ( size );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_43_p2 );
    sensitive << ( it_reg_32 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( src_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_43_p2 );

    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "forward_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, src_V_dout, "(port)src_V_dout");
    sc_trace(mVcdFile, src_V_empty_n, "(port)src_V_empty_n");
    sc_trace(mVcdFile, src_V_read, "(port)src_V_read");
    sc_trace(mVcdFile, size, "(port)size");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, src_V_blk_n, "src_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_43_p2, "tmp_fu_43_p2");
    sc_trace(mVcdFile, it_1_fu_48_p2, "it_1_fu_48_p2");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, it_reg_32, "it_reg_32");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

forward::~forward() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void forward::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_43_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(tmp_fu_43_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_V_empty_n.read())))) {
        it_reg_32 = it_1_fu_48_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        it_reg_32 = ap_const_lv16_0;
    }
}

void forward::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void forward::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void forward::thread_ap_block_state2() {
    ap_block_state2 = (esl_seteq<1,1,1>(tmp_fu_43_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_V_empty_n.read()));
}

void forward::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          !(esl_seteq<1,1,1>(tmp_fu_43_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_V_empty_n.read())) && 
          esl_seteq<1,1,1>(tmp_fu_43_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void forward::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void forward::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(tmp_fu_43_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_V_empty_n.read())) && 
         esl_seteq<1,1,1>(tmp_fu_43_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void forward::thread_it_1_fu_48_p2() {
    it_1_fu_48_p2 = (!it_reg_32.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<16>(): (sc_biguint<16>(it_reg_32.read()) + sc_biguint<16>(ap_const_lv16_1));
}

void forward::thread_src_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_43_p2.read(), ap_const_lv1_0))) {
        src_V_blk_n = src_V_empty_n.read();
    } else {
        src_V_blk_n = ap_const_logic_1;
    }
}

void forward::thread_src_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_43_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(tmp_fu_43_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_V_empty_n.read())))) {
        src_V_read = ap_const_logic_1;
    } else {
        src_V_read = ap_const_logic_0;
    }
}

void forward::thread_tmp_fu_43_p2() {
    tmp_fu_43_p2 = (!it_reg_32.read().is_01() || !size.read().is_01())? sc_lv<1>(): sc_lv<1>(it_reg_32.read() == size.read());
}

void forward::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,1,1>(tmp_fu_43_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_V_empty_n.read())) && esl_seteq<1,1,1>(tmp_fu_43_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_fu_43_p2.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(tmp_fu_43_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_V_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

